[package]
name = "day06_lanternfish_part2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day06_lanternfish_common = { path = "../day06_lanternfish_common" }
