[package]
name = "day10_syntax_scoring_part2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day10_syntax_scoring_common = { path = "../day10_syntax_scoring_common" }
