[package]
name = "day01_sonar_sweep_part1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day01_sonar_sweep_common = { path = "../day01_sonar_sweep_common" }
